sudo: required
services:
  - docker

before_install:
  - docker build -t shaodoo/docker-react -f Docker.dev .

script:
  - docker run --name docker-react shaodoo/docker-react npm run test -- --coverage
  - docker rm -f docker-react
