sudo: required
services:
  - docker

before_install:
  - docker build -t shaodoo/docker-react -f Docker.dev .

script:
  - docker run shaodoo/docker-react npm run test -- --coverage

after_script:
  - docker ps -a
  - docker stop $(docker ps -a -q)